# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Short Commit SHA env
      run: |
        $shortSha = git rev-parse --short ${{ github.sha }}
        Add-Content -Path $env:GITHUB_ENV -Value "SHORT_COMMIT_SHA=$shortSha"    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ github.workspace }}/src/HPH.ParkRunChamps.Cli/appsettings.json'
      env:
        installed.clientId: ${{ secrets.g_sheets_client_id }}
        installed.clientSecret: ${{ secrets.g_sheets_client_secret }}
    
    - name: Restore dependencies
      run: dotnet restore -r win-x64
    
    - name: Build
      run: dotnet build --no-restore -c Release --version-suffix ${{ env.SHORT_COMMIT_SHA }}
    
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
      
    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: verify-test-results
        path: |
          **/*.received.*
    
    - name: Publish
      if: success()
      run: dotnet publish .\src\HPH.ParkRunChamps.Cli\ --no-build -r win-x64 --self-contained true -c Release --version-suffix ${{ env.SHORT_COMMIT_SHA }} -o ${{ github.workspace }}\publish

    - name: Zip artifacts
      uses: vimtor/action-zip@v1.1
      with:
        files: publish\
        dest: HPH-ParkRun-Champs-${{ env.SHORT_COMMIT_SHA }}.zip
      if: success()
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: success()
      with:
        name: 1.0.0-${{ env.SHORT_COMMIT_SHA }}
        makeLatest: true
        tag: ${{ env.SHORT_COMMIT_SHA }}
        artifacts: ${{ github.workspace }}\HPH-ParkRun-Champs-${{ env.SHORT_COMMIT_SHA }}.zip
        
    - name: Upload Released Assets
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: HPH-ParkRun-Champs-${{ env.SHORT_COMMIT_SHA }}
        path: ${{ github.workspace }}\publish\*